name: Update Calendar

on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas ics

      - name: Generate calendar
        run: python generate_calendar.py

      - name: Commit calendar file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update calendar.ics
          file_pattern: calendar.ics
